spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://zemoga-test-db.crhpedy9xxto.us​-​east-1.rds.amazonaws.com:3306/zemoga_test_db
    username: zemoga_test_db
    password: Zem0ga.101
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8888
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain

info:
  owner: Eduard Reyes <reydward@gmail.com>



