spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://zemoga-test-db.crhpedy9xxto.us​-​east-1.rds.amazonaws.com:3306/zemoga_test_db
    username: zemoga_test_db
    password: Zem0ga.101
  jpa:
    hibernate:
      ddl-auto: validate

twitter:
  app-id: "QjAjb1h1rt3CGH4AZjKxy3mtO0"
  app-secret: "5ObLdPn58SlWWOIOTMan1OFiIFwl86njkenXPELtcGGHR2qSr9"
  access-token: "73032661-hs6UyaVURXuHXo6wQAwGW2BB7WzftvUoVIev9lIi5"
  access-token-secret: "euVhfz47eX1hFyfhyXVv9fto7sUIPVHg9jRojecOgbaRP"

server:
  port: 8888
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain

info:
  owner: Eduard Reyes <reydward@gmail.com>